tidak mengerjakan tidak boleh masuk!!

- berikan penjelasan tentang apa itu matrik
-operasi matrik
-penjumlahan,perkalian,pengurangan,transpose matrik
- buat program untuk mengalikan matrik a dan b

In [23]:
import numpy as np
a = np.array([[2,4,1],[0,5,7],[3,8,6]])#matrik 3x3
b = np.array([[-2,6,0],[4,1,-3],[2,7,5]])#matrik 3x3
c = np.array([[3,1],[-2,5],[0,7]])#matrik 3x2
d = np.array([[1,4],[6,-1],[2,0]])#matrik 3x2
print('a+b=' ,a@b)


a= [[2 4 1]
 [0 5 7]
 [3 8 6]]

a+b= [[14 23 -7]
 [34 54 20]
 [38 68  6]]


In [40]:
#contoh e
import numpy as np
a = np.array([[2,3,1],[0,5,2]])
print('a=' ,a)
print()
b = np.array([[-2,5,0],[-1,2,-3]])
print('b=' ,b)
print()
c = np.array([[4,1,3],[1,5,7]])
print('c=' ,c)
print()


a= [[2 3 1]
 [0 5 2]]

b= [[-2  5  0]
 [-1  2 -3]]

c= [[4 1 3]
 [1 5 7]]



In [59]:
import numpy as np
a = np.array([[2,3,1],[0,7,2],[1,4]])
b = np.array([[-2,5,0],[-1,2,-3]])
c = np.array([[4,1,3],[1,5,7],[7,2,0]])
d = np.array([[5,8,0],[2,5,-1]])
e = np.array([[1,4,5],[6,-1,2]])
f = np.array([[2,4,1],[0,5,7],[3,8,6]])
g = a @ c
c = 3
print (f"e adalah a+b = \n {a+b}")  # menguunakan for
print (f"f adalah 2xa = \n {2*a}")
print (f"g adalah axc = \n {a@c}")
print (g.shape)
print (f"h adalah a@(b@c) = \n {a@(b@c)}")
print (f"i adalah a+b = \n {(a@b)@c}")
print (f"k adalah a+b = \n {c(a@b)}")
print (f"l adalah a+b = \n {(a@b)}")

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.